# Generated by Django 5.2.7 on 2025-10-06 22:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('PR', 'Prospect'), ('IP', 'In Progress'), ('OH', 'On Hold'), ('CP', 'Completed'), ('CN', 'Cancelled')], default='PR', max_length=10)),
                ('value', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('primary_contacts', models.ManyToManyField(related_name='assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFPDocument',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key='file_id', serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
