# Generated by Django 5.2.7 on 2025-10-06 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpdocument',
            name='document_file',
            field=models.FileField(default=None, upload_to='rfp_documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfpdocument',
            name='file_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rfpdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
